// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4yOe9bY1ed1_u3dZziv3m32MGJmFNrFg',
    appId: '1:411827572344:web:ee20ce5d1be11c3747278d',
    messagingSenderId: '411827572344',
    projectId: 'flower-store-67ee9',
    authDomain: 'flower-store-67ee9.firebaseapp.com',
    storageBucket: 'flower-store-67ee9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT3BYiccn90S6WAqX84isb7HN4cPK8neM',
    appId: '1:411827572344:android:0ea1b98efada9a3047278d',
    messagingSenderId: '411827572344',
    projectId: 'flower-store-67ee9',
    storageBucket: 'flower-store-67ee9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGwdLTVjDhfhYIUsvUxAWyOSc6kJq8w1s',
    appId: '1:411827572344:ios:dc5faa10fc5c1dee47278d',
    messagingSenderId: '411827572344',
    projectId: 'flower-store-67ee9',
    storageBucket: 'flower-store-67ee9.appspot.com',
    iosClientId: '411827572344-4vlg22sdstlm9fk9qoptkgl2h555i3og.apps.googleusercontent.com',
    iosBundleId: 'com.example.userflowerstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGwdLTVjDhfhYIUsvUxAWyOSc6kJq8w1s',
    appId: '1:411827572344:ios:dc5faa10fc5c1dee47278d',
    messagingSenderId: '411827572344',
    projectId: 'flower-store-67ee9',
    storageBucket: 'flower-store-67ee9.appspot.com',
    iosClientId: '411827572344-4vlg22sdstlm9fk9qoptkgl2h555i3og.apps.googleusercontent.com',
    iosBundleId: 'com.example.userflowerstore',
  );
}
